/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 26 14:39:05 GMT 2024
 */

package testing_ChatGPT_on_java;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.InputMismatchException;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.util.SystemInUtil;
import org.junit.runner.RunWith;
import testing_ChatGPT_on_java.OctalToBinary;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class OctalToBinary_ESTest extends OctalToBinary_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      int int0 = OctalToBinary.convertOctalToDecimal(0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      int int0 = OctalToBinary.convertOctalToDecimal((-595));
      assertEquals((-397), int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      int int0 = OctalToBinary.convertDecimalToBinary(0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      int int0 = OctalToBinary.convertDecimalToBinary((-501));
      assertEquals((-111110101), int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      String[] stringArray0 = new String[9];
      SystemInUtil.addInputLine("pDLe3Cn]lka8n*z;[");
      // Undeclared exception!
      try { 
        OctalToBinary.main(stringArray0);
        fail("Expecting exception: InputMismatchException");
      
      } catch(InputMismatchException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      int int0 = OctalToBinary.convertDecimalToBinary(238);
      assertEquals(11101110, int0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      int int0 = OctalToBinary.convertOctalToDecimal(356);
      assertEquals(238, int0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      String[] stringArray0 = new String[2];
      SystemInUtil.addInputLine("57");
      OctalToBinary.main(stringArray0);
      assertEquals(2, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      OctalToBinary octalToBinary0 = new OctalToBinary();
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      String[] stringArray0 = new String[2];
      // Undeclared exception!
      try { 
        OctalToBinary.main(stringArray0);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }
}
