/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 03 12:26:49 GMT 2024
 */

package testing_ChatGPT_on_java;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import testing_ChatGPT_on_java.MultithreadedSort;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MultithreadedSort_ESTest extends MultithreadedSort_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      int[] intArray0 = new int[9];
      intArray0[2] = 1;
      MultithreadedSort.mergeSort(intArray0, 1, 4);
      assertArrayEquals(new int[] {0, 0, 0, 0, 1, 0, 0, 0, 0}, intArray0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      int[] intArray0 = new int[9];
      intArray0[1] = (-210);
      MultithreadedSort.mergeSort(intArray0, 1, 4);
      assertArrayEquals(new int[] {0, (-210), 0, 0, 0, 0, 0, 0, 0}, intArray0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      int[] intArray0 = new int[9];
      MultithreadedSort.mergeSort(intArray0, 2010, (-3224));
      assertArrayEquals(new int[] {0, 0, 0, 0, 0, 0, 0, 0, 0}, intArray0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      int[] intArray0 = new int[6];
      // Undeclared exception!
      try { 
        MultithreadedSort.mergeSort(intArray0, 9, 242);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 9
         //
         verifyException("testing_ChatGPT_on_java.MultithreadedSort", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      // Undeclared exception!
      try { 
        MultithreadedSort.merge((int[]) null, (-1103), 0, 1381);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("testing_ChatGPT_on_java.MultithreadedSort", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      int[] intArray0 = new int[5];
      // Undeclared exception!
      try { 
        MultithreadedSort.merge(intArray0, 0, 6, (-2345));
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("testing_ChatGPT_on_java.MultithreadedSort", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      int[] intArray0 = new int[5];
      // Undeclared exception!
      try { 
        MultithreadedSort.merge(intArray0, (-5465), 0, 0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -5465
         //
         verifyException("testing_ChatGPT_on_java.MultithreadedSort", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      int[] intArray0 = new int[9];
      intArray0[0] = 2080;
      MultithreadedSort.merge(intArray0, 0, 0, 7);
      assertArrayEquals(new int[] {0, 0, 0, 0, 0, 0, 0, 2080, 0}, intArray0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      int[] intArray0 = new int[12];
      MultithreadedSort.merge(intArray0, 0, 0, 7);
      assertEquals(12, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      // Undeclared exception!
      try { 
        MultithreadedSort.mergeSort((int[]) null, 0, 1277);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("testing_ChatGPT_on_java.MultithreadedSort", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      int[] intArray0 = new int[2];
      MultithreadedSort.mergeSort(intArray0, (-563), (-563));
      assertEquals(2, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      MultithreadedSort multithreadedSort0 = new MultithreadedSort();
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      String[] stringArray0 = new String[3];
      MultithreadedSort.main(stringArray0);
      MultithreadedSort.main(stringArray0);
      MultithreadedSort.main(stringArray0);
      MultithreadedSort.main(stringArray0);
      MultithreadedSort.main(stringArray0);
      MultithreadedSort.main(stringArray0);
      // Undeclared exception!
      MultithreadedSort.main(stringArray0);
  }
}
