/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 03 12:31:10 GMT 2024
 */

package testing_ChatGPT_on_java;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import testing_ChatGPT_on_java.ParallelSort;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ParallelSort_ESTest extends ParallelSort_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String[] stringArray0 = new String[4];
      stringArray0[0] = "ycJK%VrN>f";
      stringArray0[1] = "{*V!.Xd; ";
      stringArray0[2] = "";
      stringArray0[3] = "";
      ParallelSort.main(stringArray0);
      ParallelSort parallelSort0 = new ParallelSort();
      ParallelSort.main(stringArray0);
      ParallelSort.main(stringArray0);
      // Undeclared exception!
      ParallelSort.main(stringArray0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ParallelSort parallelSort0 = new ParallelSort();
      String[] stringArray0 = new String[6];
      stringArray0[0] = "After sorting: ";
      stringArray0[1] = "ugAx?SQF";
      stringArray0[2] = "3}Z~I9&h,+l&ZuU0s";
      stringArray0[3] = "testing_ChatGPT_on_java.ParallelSort";
      stringArray0[4] = "A k9~m[K108v(06";
      stringArray0[5] = "jj9E~O";
      ParallelSort.main(stringArray0);
      String[] stringArray1 = new String[1];
      String string0 = "";
      stringArray1[0] = "";
      ParallelSort.main(stringArray1);
      int[] intArray0 = new int[3];
      intArray0[0] = 0;
      intArray0[1] = 0;
      intArray0[2] = 0;
      ParallelSort.SortTask parallelSort_SortTask0 = new ParallelSort.SortTask(intArray0, (-2110), 0);
      // Undeclared exception!
      try { 
        parallelSort_SortTask0.run();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Array index out of range: -2110
         //
         verifyException("java.util.Arrays", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      int[] intArray0 = new int[5];
      intArray0[0] = 3;
      intArray0[1] = (-500);
      intArray0[2] = 1525;
      intArray0[3] = 0;
      intArray0[4] = 0;
      ParallelSort.SortTask parallelSort_SortTask0 = new ParallelSort.SortTask(intArray0, 3, 3);
      parallelSort_SortTask0.run();
      String[] stringArray0 = new String[5];
      stringArray0[0] = "V<tJK";
      stringArray0[1] = "testing_ChatGPT_on_java.ParallelSort";
      stringArray0[2] = "";
      stringArray0[3] = "";
      stringArray0[4] = "571YQvHP";
      ParallelSort.main(stringArray0);
      assertEquals(5, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      int[] intArray0 = new int[8];
      intArray0[0] = 0;
      intArray0[1] = 1379;
      intArray0[2] = (-1);
      intArray0[3] = 1392;
      intArray0[4] = 0;
      intArray0[5] = 0;
      intArray0[6] = 1;
      intArray0[7] = 0;
      ParallelSort.SortTask parallelSort_SortTask0 = new ParallelSort.SortTask(intArray0, 1516, 0);
  }
}
