/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 03 12:19:57 GMT 2024
 */

package testing_ChatGPT_on_java;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import testing_ChatGPT_on_java.EvenOddThread;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class EvenOddThread_ESTest extends EvenOddThread_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      EvenOddThread.OddNumberThread evenOddThread_OddNumberThread0 = new EvenOddThread.OddNumberThread();
      evenOddThread_OddNumberThread0.run();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      EvenOddThread.EvenNumberThread evenOddThread_EvenNumberThread0 = new EvenOddThread.EvenNumberThread();
      evenOddThread_EvenNumberThread0.run();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      String[] stringArray0 = new String[1];
      EvenOddThread.main(stringArray0);
      assertEquals(1, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      EvenOddThread evenOddThread0 = new EvenOddThread();
  }
}
