/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 03 12:23:06 GMT 2024
 */

package testing_ChatGPT_on_java;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import testing_ChatGPT_on_java.Find_Even_Odd_Number;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Find_Even_Odd_Number_ESTest extends Find_Even_Odd_Number_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Find_Even_Odd_Number find_Even_Odd_Number0 = new Find_Even_Odd_Number();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String[] stringArray0 = new String[4];
      Find_Even_Odd_Number.main(stringArray0);
      assertEquals(4, stringArray0.length);
  }
}
