/*
 * This file was automatically generated by EvoSuite
 * Thu Mar 28 15:36:49 GMT 2024
 */

package testing_ChatGPT_on_java;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import testing_ChatGPT_on_java.ScheduledTaskExample;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ScheduledTaskExample_ESTest extends ScheduledTaskExample_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String[] stringArray0 = new String[9];
      ScheduledTaskExample.main(stringArray0);
      assertEquals(9, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ScheduledTaskExample scheduledTaskExample0 = new ScheduledTaskExample();
  }
}
