/*
 * This file was automatically generated by EvoSuite
 * Thu Mar 28 15:41:34 GMT 2024
 */

package testing_ChatGPT_on_java;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import testing_ChatGPT_on_java.ScheduledExecutorExercise;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ScheduledExecutorExercise_ESTest extends ScheduledExecutorExercise_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String[] stringArray0 = new String[8];
      stringArray0[0] = "";
      stringArray0[1] = "";
      stringArray0[2] = "B1{P7N@|mZg:W1kB";
      stringArray0[3] = "";
      stringArray0[4] = "Task executed at: ";
      stringArray0[5] = "lV/GecM#XYMz5a+*%q-";
      stringArray0[6] = "Ti2?]Dm_Ju";
      stringArray0[7] = "n=h[aH(\"G4BY;j@1j";
      ScheduledExecutorExercise.main(stringArray0);
      ScheduledExecutorExercise.main(stringArray0);
      ScheduledExecutorExercise.Task scheduledExecutorExercise_Task0 = new ScheduledExecutorExercise.Task();
      scheduledExecutorExercise_Task0.run();
      ScheduledExecutorExercise.Task scheduledExecutorExercise_Task1 = new ScheduledExecutorExercise.Task();
      scheduledExecutorExercise_Task1.run();
      ScheduledExecutorExercise.main(stringArray0);
      scheduledExecutorExercise_Task0.run();
      scheduledExecutorExercise_Task1.run();
      scheduledExecutorExercise_Task0.run();
      scheduledExecutorExercise_Task1.run();
      ScheduledExecutorExercise scheduledExecutorExercise0 = new ScheduledExecutorExercise();
      scheduledExecutorExercise_Task1.run();
      ScheduledExecutorExercise.main(stringArray0);
      scheduledExecutorExercise_Task0.run();
      assertFalse(scheduledExecutorExercise_Task0.equals((Object)scheduledExecutorExercise_Task1));
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ScheduledExecutorExercise scheduledExecutorExercise0 = new ScheduledExecutorExercise();
      String[] stringArray0 = new String[1];
      stringArray0[0] = "testing_ChatGPT_on_java.ScheduledExecutorExercise";
      ScheduledExecutorExercise.main(stringArray0);
      String[] stringArray1 = new String[0];
      ScheduledExecutorExercise.main(stringArray1);
      ScheduledExecutorExercise.main((String[]) null);
  }
}
