/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 03 11:40:58 GMT 2024
 */

package testing_ChatGPT_on_java;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import testing_ChatGPT_on_java.SharedCounterExample;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SharedCounterExample_ESTest extends SharedCounterExample_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SharedCounterExample.main((String[]) null);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SharedCounterExample.CounterIncrementer sharedCounterExample_CounterIncrementer0 = new SharedCounterExample.CounterIncrementer();
      sharedCounterExample_CounterIncrementer0.run();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SharedCounterExample sharedCounterExample0 = new SharedCounterExample();
  }
}
