/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 12 13:11:43 GMT 2024
 */

package testing_ChatGPT_on_java;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import testing_ChatGPT_on_java.Pet;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Pet_ESTest extends Pet_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Pet pet0 = new Pet("~", 22.564083235583066, "~");
      pet0.setWeight(22.564083235583066);
      pet0.getType();
      pet0.setName("~");
      pet0.setType("~");
      String[] stringArray0 = new String[1];
      Pet.main(stringArray0);
      pet0.getWeight();
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Pet pet0 = new Pet("4pYw", 0.0, "4pYw");
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = "";
      Pet.main(stringArray0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Pet pet0 = new Pet("Whiskers", 0.0, "Whiskers");
      pet0.setWeight(0.0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Pet pet0 = new Pet("", 989.9, "");
      pet0.getWeight();
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Pet pet0 = new Pet("", (-2723.956408500938), "");
      pet0.getType();
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Pet pet0 = new Pet((String) null, 0.03, (String) null);
      pet0.setType((String) null);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Pet pet0 = new Pet("1;!^s\"W", 0.0, "");
      pet0.setName("1;!^s\"W");
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Pet pet0 = new Pet("tg[Nxsm1=DcY%4-", 0.0, "tg[Nxsm1=DcY%4-");
      pet0.setName("tg[Nxsm1=DcY%4-");
      pet0.getType();
      pet0.getWeight();
      pet0.setName("tg[Nxsm1=DcY%4-");
      pet0.getType();
      pet0.getName();
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Pet pet0 = new Pet("", (-290.2450167890423), "");
      pet0.getWeight();
      pet0.setType((String) null);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Pet pet0 = new Pet("", (-1431.746036457335), "6S+{");
      pet0.acepromazine();
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Pet pet0 = new Pet("i&xojs[;;P<rBe", (-610.41543459), "i&xojs[;;P<rBe");
      pet0.setType("bDj]j6Gl<NpD)U ");
      pet0.getType();
      pet0.getType();
      pet0.getWeight();
      pet0.carprofen();
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Pet pet0 = new Pet("txJX,p", 0.0, "txJX,p");
      pet0.getWeight();
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Pet pet0 = new Pet((String) null, 0.0, "");
      pet0.acepromazine();
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Pet pet0 = new Pet("", 69.091, "");
      pet0.acepromazine();
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Pet pet0 = new Pet("\"mV[AO8IK5eQ-8 \"x!", 0.0, "\"mV[AO8IK5eQ-8 \"x!");
      pet0.setName("\"mV[AO8IK5eQ-8 \"x!");
      String[] stringArray0 = new String[1];
      stringArray0[0] = "\"mV[AO8IK5eQ-8 \"x!";
      pet0.setName("\"mV[AO8IK5eQ-8 \"x!");
      pet0.setWeight(0.0);
      Pet.main(stringArray0);
      pet0.getType();
      pet0.carprofen();
      pet0.carprofen();
      pet0.getWeight();
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Pet pet0 = new Pet("@L|_STNWBp/,*p", 3507.27, "@L|_STNWBp/,*p");
      pet0.carprofen();
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Pet pet0 = new Pet("", (-3217.100478273836), "dog");
      String[] stringArray0 = new String[4];
      stringArray0[0] = "dog";
      stringArray0[1] = "";
      stringArray0[2] = "~P${V6VwS'Q WD";
      stringArray0[3] = "";
      Pet.main(stringArray0);
      pet0.setName("");
      pet0.setType("dog");
      pet0.carprofen();
      Pet.main(stringArray0);
      pet0.setWeight(52.6386707395948);
      pet0.acepromazine();
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Pet pet0 = new Pet((String) null, (-2042.0), (String) null);
      pet0.setType("HmaouydmN");
      pet0.setName((String) null);
      pet0.acepromazine();
      String[] stringArray0 = new String[4];
      pet0.setType("<l6-A3&-1{bRA)Ua~");
      stringArray0[0] = "HmaouydmN";
      stringArray0[1] = null;
      stringArray0[1] = null;
      stringArray0[3] = "HmaouydmN";
      Pet.main(stringArray0);
      pet0.getName();
      pet0.carprofen();
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      String string0 = null;
      Pet pet0 = new Pet((String) null, 1.0, (String) null);
      pet0.setType((String) null);
      pet0.getType();
      pet0.setWeight(1.0);
      pet0.getWeight();
      pet0.setWeight((-2483.5));
      pet0.getType();
      pet0.carprofen();
      pet0.setName(string0);
      String string1 = "dMS1LgiMwopPc+";
  }
}
